<a href="https://colab.research.google.com/github/JakeOh/202007_iw_pyda_wkd/blob/master/py09_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: Numerical Python. 다차원 배열을 빠르게 계산할 수 있는 패키지.
<br>
<br>
모듈(module): 확장자 py인 파이썬 파일. 함수를 정의. 클래스 정의. 변수 선언/초기화.
<br>
패키지(package): 모듈(py 파일)들의 꾸러미. 파일들을 저장하고 있는 디렉토리.


In [1]:
import numpy as np

print(np.__version__)

1.18.5


In [4]:
# Python 기본 타입 list 클래스와 NumPy ndarray 클래스의 차이점
number_list = [1, 2, 3, 4, 5]  # list
print(type(number_list))
print(number_list)

number_array = np.array([1, 2, 3, 4, 5])  # numpy.ndarray
print(type(number_array))
print(number_array)

<class 'list'>
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
list_2d = [[1, 2, 3],
           [4, 5, 6]]
print(list_2d)

[[1, 2, 3], [4, 5, 6]]


In [7]:
array_2d = np.array(list_2d)
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
# list는 + 연산과 * 연산만 가능.
# list는 -, /, //, %, ** 등의 연산은 제공하지 않음.
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1 + l2)  # list + 연산: concatenate
print(l1 * 3)  # list * 연산: 원소들을 반복해서 리스트의 원소 개수를 늘림.

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [13]:
# numpy.ndarray는 모든 산술 연산(+, -, *, /, //, %, **) 가능.
# 같은 위치의 원소들끼리 산술 연산을 수행(element-wise operation).
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1 + a2)
print(a1 * a2)
print(a1 ** 3)

[5 7 9]
[ 4 10 18]
[ 1  8 27]


In [16]:
# list와 numpy.ndarray는 인덱스를 사용
print(l1[0])  # 1-d list
print(a1[0])  # 1-d array

print(list_2d[0][0])  # 2-d list
print(array_2d[0, 0])  # 2-d array

1
1
1
1


In [21]:
# numpy.ndarray를 생성하는 함수들
arr1 = np.arange(1, 11, 1)
print(arr1)
# ndarray의 속성들(attributes)
print(arr1.shape)  # 각 축(axis)의 차원(원소, dimensionality) 개수
print(arr1.size)  # 원소의 개수
print(arr1.ndim)  # 차원 개수
print(arr1.dtype)  # 원소들의 데이터 타입

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
10
1
int64


In [27]:
arr2 = np.ones(shape=5, dtype=np.int32)
print(arr2)
print(arr2.dtype)
print('ndim:', arr2.ndim)
print('shape:', arr2.shape)
print('size:', arr2.size)

[1 1 1 1 1]
int32
ndim: 1
shape: (5,)
size: 5


In [32]:
arr3 = np.ones(shape=(2, 3))
print(arr3)
print('dtype:', arr3.dtype)
print('ndim:', arr3.ndim)
print('shape:', arr3.shape)
print('size:', arr3.size)

[[1. 1. 1.]
 [1. 1. 1.]]
dtype: float64
ndim: 2
shape: (2, 3)
size: 6


In [33]:
arr4 = np.zeros(shape=(3, 3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
arr5 = np.eye(N=3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
arr6 = np.random.rand(5)  # 0 <= r < 1 범위의 난수로 array 생성
print(arr6)

arr7 = np.random.rand(2, 3)
print(arr7)

[0.51811247 0.17283925 0.95997655 0.75554953 0.80810562]
[[0.9275398  0.221477   0.96670632]
 [0.18149651 0.34826149 0.87888497]]


In [49]:
# 평균이 0이고, 표준편차가 1인 표준 정규분포(normal distribution)를 따르는 
# 난수를 사용해서 array를 생성.
arr8 = np.random.randn(2, 3)
print(arr8)

[[ 0.92604541  0.87300393 -1.86856826]
 [ 0.9386328   1.5225841  -0.32881755]]


In [59]:
arr9 = np.random.randint(0, 10, size=10)
print(arr9)

arr10 = np.random.randint(0, 10, size=(3, 4))
print(arr10)

[7 7 9 5 8 8 7 2 0 8]
[[4 6 3 4]
 [5 8 0 6]
 [2 4 7 5]]


In [64]:
arr = np.arange(1, 13)
print(arr)
print(arr.reshape((3, 4)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
arr = np.arange(1, 13).reshape((4, 3))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
