<a href="https://colab.research.google.com/github/JakeOh/202007_iw_pyda_wkd/blob/master/py10_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.__version__

'1.18.5'

In [3]:
# 표준 정규분포를 따르는 난수를 이용해서 원소 10개인 1차원 array를 생성
array = np.random.randn(10)
array

array([ 0.97631728, -0.1625761 ,  0.78136637,  0.05162783, -0.39983685,
       -1.98620867,  1.53937579,  0.41716208, -1.51045779, -1.46797691])

In [4]:
array > 0

array([ True, False,  True,  True, False, False,  True,  True, False,
       False])

In [5]:
# boolean indexing
array[array > 0]

array([0.97631728, 0.78136637, 0.05162783, 1.53937579, 0.41716208])

In [6]:
array = np.random.randn(3, 3)
print(array)

[[-1.7517782  -0.47500687  0.70085234]
 [-0.56011265  0.19529202 -0.83967696]
 [-0.58138092 -0.20515755  0.11263852]]


In [7]:
array[array > 0]

array([0.70085234, 0.19529202, 0.11263852])

In [9]:
# boolean indexing을 사용할 때는 &, |, ~ 연산자를 사용할 수 있음.
# 2개의 조건을 &, |로 연결할 때는 반드시 ()를 사용해야 함!
array = np.random.randn(10)
print(array)

# array에서 -0.5 <= x <= 0.5 범위의 숫자들만 선택
array[(array >= -0.5) & (array <= 0.5)]

[-0.30606646 -1.37213806 -0.07546732 -0.91705057 -1.55540226 -0.31187846
  0.10335659  0.29539014 -0.81168356  0.94162945]


array([-0.30606646, -0.07546732, -0.31187846,  0.10335659,  0.29539014])

In [11]:
# broadcast
a1 = np.array([[1, 1, 2],
               [2, 2, 3],
               [3, 3, 4]])
a2 = np.array([1, 2, 3])
print(a1)
print(a2)

[[1 1 2]
 [2 2 3]
 [3 3 4]]
[1 2 3]


In [12]:
print(a1 + a2)

[[2 3 5]
 [3 4 6]
 [4 5 7]]
